version: '3'
services:
    postgresql-database:
        image: debezium/postgres:9.6
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=postgres
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    redis-seo:
        image: redis
        ports:
            - "6379:6379"

